# Change these first
owner: StroyCo # Your GitHub organization or username, where this repository lives
repo: stroy-up # The name of this repository

sites:
  #- name: Portfolio
  #  url: https://portfolio.stroyco.eu
  - name: Jellyfin
    url: https://jelly.stroyco.eu
  - name: Jellyseer
    url: https://jellyseerr.stroyco.eu
  #- name: SeRA
  #  url: https://develop-sera.stroyco.eu
  - name: StroyGetter
    url: https://stroygetter.stroyco.eu
  - name: StroyBot
    url: https://stroybot.stroyco.eu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /stroy-up
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: StroyUp
  #introTitle: ""
  #introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
